---
- name: Set http_can_network_connect flag on and keep it persistent across reboots
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true
- name: Enable services on the VM Host
  ansible.posix.firewalld:
    service: "{{ srv_name }}"
    permanent: true
    state: enabled
  loop:
    - https
  loop_control:
    loop_var: srv_name
- name: Stop firewalld
  ansible.builtin.service:
    name: firewalld
    state: stopped
- name: Start firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
