---
- name: Prepare the host for sonarqube
  hosts: "{{ inventory_group_name | default('sonarqube') }}"
  # connection: local
  become: true
  vars_files:
    - ./vars/main.yml
  tasks:
    - name: Setup Podman socket permissions
      ansible.builtin.include_role:
        name: jamesjonesconsulting.podman_socket_group_permissions.permissions_setup
      vars:
        podman_user_group: docker
        podman_users:
          - jam
    - name: Setup firewall
      ansible.builtin.include_tasks: firewall.yml
    - name: Adding some folders for binding
      ansible.builtin.file:
        path: "{{ sqpath }}"
        state: directory
        owner: 1001
        group: 1001
        mode: 0755
      loop:
        - /opt/sonarqube
      loop_control:
        loop_var: sqpath
    # - name: Install certbot
    #   ansible.builtin.yum:
    #     name: certbot
    #     state: present
    # - name: Install openssl and OpenJDK 11
    #   ansible.builtin.yum:
    #     name:
    #       - openssl
    #       - java-11-openjdk-headless
    #     state: present
    # - name: Create a temp directory for Docker files
    #   ansible.builtin.tempfile:
    #     state: directory
    #     suffix: docker
    #   register: dck_path
    # - name: Copy over the Dockerfile's
    #   ansible.builtin.copy:
    #     src: "files/{{ dkrfile }}"
    #     dest: "{{ dck_path.path }}/{{ dkrfile }}"
    #     mode: 0755
    #   loop:
    #     - Dockerfile.nexus3
    #     - Dockerfile.openldap
    #     - enablenexusplugins.py
    #   loop_control:
    #     loop_var: dkrfile
    # - name: Setup the OpenLDAP container tasks
    #   ansible.builtin.include_tasks: openldap-podman.yml
    #   vars:
    #     container:
    #       path: "{{ dck_path.path }}"
    #       dockerfile: Dockerfile.openldap
    #       tag: "{{ lookup('env', 'OPENLDAP_TAG_VERSION') }}"
    #       hostname: "{{ lookup('env', 'HOST_NAME') }}"
    #     ldap:
    #       admin:
    #         username: "{{ lookup('env', 'LDAP_ADMIN_USER') }}"
    #         password: "{{ lookup('env', 'LDAP_ADMIN_PASSWORD') }}"
    #       users: "{{ lookup('env', 'LDAP_USER') }}"
    #       passwords: "{{ lookup('env', 'LDAP_PASSWORD') }}"
    #       root: "{{ lookup('env', 'LDAP_ROOT') }}"
    #       tls:
    #         enabled: true
    # - name: Setup the Nexus container tasks
    #   ansible.builtin.include_tasks: nexus-podman.yml
    #   vars:
    #     container:
    #       path: "{{ dck_path.path }}"
    #       dockerfile: Dockerfile.nexus3
    #       tag: "{{ lookup('env', 'TAG_VERSION') }}"
    #       hostname: "{{ lookup('env', 'HOST_NAME') }}"
    # - name: Remove the temporary directory
    #   ansible.builtin.file:
    #     path: "{{ dck_path.path }}"
    #     state: absent
    #   when: "dck_path.path is defined"
