---
- name: Prepare the host for sonarqube
  hosts: "{{ inventory_group_name | default('sonarqube') }}"
  # connection: local
  become: true
  vars_files:
    - ./vars/main.yml
  tasks:
    - name: Setup Podman socket permissions
      ansible.builtin.include_role:
        name: jamesjonesconsulting.podman_socket_group_permissions.permissions_setup
      vars:
        podman_user_group: docker
        podman_users:
          - jam
    - name: Setup firewall
      ansible.builtin.include_tasks: firewall.yml
    - name: Setup the Nexus container tasks
      ansible.builtin.include_tasks: sonarqube-podman.yml
      vars:
        container:
          image: "{{ lookup('env', 'IMAGE_NAME') }}"
          tag: "{{ lookup('env', 'TAG_VERSION') }}"
          hostname: "{{ lookup('env', 'HOST_NAME') }}"
